services:
  - type: web
    name: dr-r-simple
    runtime: python
    plan: free
    buildCommand: "bash build.sh"
    startCommand: "gunicorn dr_r.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: dr_r.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: GROQ_API_KEY
        sync: false
